# 订阅源URL列表
subscription_urls:
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub2.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub4.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub5.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub6.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub7.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub8.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub9.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub10.txt"
  # - "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub11.txt"
  # - "https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/server.txt"
  # - "https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub"
  - "https://mangaharb.fun:7643/v2ray/available_links.txt"

# 目标站点配置
target_hosts:
  "91mh01.xyz":
    display_name: "91mh01"
  "www.wnacg.com":
    display_name: "wnacg"

# 获取器配置
fetcher:
  timeout: 10
  retry_times: 3
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"

# 测试器配置
testers:
  # 默认配置
  concurrent_tests: 5      # 默认并发数
  connect_timeout: 10      # 默认连接超时
  retry_times: 2          # 默认重试次数
  
  # TCP测试器
  tcp_tester:
    enabled: true         # 是否启用
    concurrent_tests: 10  # 覆盖默认并发数
    connect_timeout: 5    # 覆盖默认超时
  
  # Glider测试器
  glider_tester:
    enabled: true
    # 使用默认配置
    check_url: "http://www.msftconnecttest.com/connecttest.txt"  # glider特有配置
    check_expect: "200"
    check_interval: 30
    check_timeout: 10
    max_failures: 3
  
  # Xray测试器
  xray_tester:
    enabled: false        # 暂时禁用
    concurrent_tests: 5
    connect_timeout: 10
  
  # SSH测试器
  ssh_tester:
    enabled: false        # 暂时禁用
    concurrent_tests: 3
    connect_timeout: 15
    key_path: "~/.ssh/id_rsa"  # ssh特有配置
    known_hosts: false

# 输出配置
output:
  # 备份配置
  backup:
    enabled: true
    dir: "results/backup"
    keep: 10
    compress: false

# 日志配置
log:
  level: "info"          # debug/info/warning/error
  file: "logs/autoSubscribe.log"
  console: true
  format: "{time} {level}: {message}"
  rotate: true           # 是否轮转日志
  max_size: "10M"        # 单个日志文件最大大小
  keep: 7               # 保留天数